In [1]:
import numpy as np

In [6]:
a = np.arange(10)
a = np.reshape(a,(2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
a<4

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [9]:
# or 조건 any
np.any(a>5)

True

In [11]:
# and 조건 all
np.all(a>5)

False

In [31]:
b = np.random.randint(1,10,10).reshape((2,5))
b

array([[8, 7, 8, 8, 2],
       [4, 6, 8, 5, 3]])

In [32]:
(a>b).any()

True

In [33]:
(a<b).any()

True

In [34]:
np.logical_and(b>5,b<7)

array([[False, False, False, False, False],
       [False,  True, False, False, False]])

### np.where

In [38]:
# where(조건,참일때 값, 거짓일때 값)
np.where(a>5,3,2)

array([[2, 2, 2, 2, 2],
       [2, 3, 3, 3, 3]])

###  argmax & argmin

In [46]:
a = np.random.randint(1,100,10)
print(a)
print(f'최대값의 인덱스{np.argmax(a)}, 최소값의 인덱스{np.argmin(a)}')

[47 59 11  1 47 35 26 97 15 44]
최대값의 인덱스7, 최소값의 인덱스3


### fancy index

In [52]:
a = np.array([2,4,6,8],float)
b = np.array([0,0,2,1,3],int)
a[b]

array([2., 2., 6., 4., 8.])

In [49]:
# a[b]와 동일한 기능 take
a.take(b)

array([2, 2, 6, 4, 8])

### loadtxt & savetxt

In [59]:
a_int = a.astype(int)
a_int

array([2, 4, 6, 8])

In [60]:
np.savetxt('int_data.csv',a_int,delimiter=',')

In [61]:
new_a = np.loadtxt("./int_data.csv")
new_a

array([2., 4., 6., 8.])

### numpy object -npy

In [63]:
# npy 확장자로 저장
np.save("npy_test_object",arr = a_int)